CREATE TABLE COUPON (
    COUPON_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    COUPON_TYPE VARCHAR(255) NOT NULL,
    DISCOUNT DECIMAL(10, 2) NOT NULL,
    COUPON_CONDITION VARCHAR(255),
    THRESHOLD DECIMAL(10, 2) NOT NULL,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    COUPON_EXPIRATION_TIME TIMESTAMP 
);

